### ISSUE TITLE
no such option: interface_driver

### ISSUE THREAD

**Issue by trihoangvo** [redhat-cip/neutron-l3-healthcheck#4]
Hi Emilien Macchi,

the config "interface_driver" has been moved away to neutron.agent.common.config.py
So it causes NoSuchOptError.

Can you update your script?

`2015-08-05 18:44:11.701 949 CRITICAL l3healthcheck [req-8529f2e6-dbc6-4753-9d02-537c55411c3a
 None] no such option: interface_driver
2015-08-05 18:44:11.701 949 TRACE l3healthcheck Traceback (most recent call last):
2015-08-05 18:44:11.701 949 TRACE l3healthcheck   File "/usr/bin/neutron-l3-healthcheck", line 338, in <module>
2015-08-05 18:44:11.701 949 TRACE l3healthcheck     main()
2015-08-05 18:44:11.701 949 TRACE l3healthcheck   File "/usr/bin/neutron-l3-healthcheck", line 323, in main
2015-08-05 18:44:11.701 949 TRACE l3healthcheck     server = L3healthcheck(socket.gethostname())
2015-08-05 18:44:11.701 949 TRACE l3healthcheck   File "/usr/bin/neutron-l3-healthcheck", line 307, in __init__
2015-08-05 18:44:11.701 949 TRACE l3healthcheck     self.manager = L3healthcheckManager(host)
2015-08-05 18:44:11.701 949 TRACE l3healthcheck   File "/usr/bin/neutron-l3-healthcheck", line 259, in __init__
2015-08-05 18:44:11.701 949 TRACE l3healthcheck     self.l3_hc_agent = L3HealthcheckAgent(host)
2015-08-05 18:44:11.701 949 TRACE l3healthcheck   File "/usr/bin/neutron-l3-healthcheck", line 111, in __init__
2015-08-05 18:44:11.701 949 TRACE l3healthcheck     if not self.conf.interface_driver:
2015-08-05 18:44:11.701 949 TRACE l3healthcheck   File "/usr/lib/python2.7/dist-packages/oslo/config/cfg.py", line 1648, in __getattr__
2015-08-05 18:44:11.701 949 TRACE l3healthcheck     raise NoSuchOptError(name)
2015-08-05 18:44:11.701 949 TRACE l3healthcheck NoSuchOptError: no such option: interface_driver`

**Comment by EmilienM** [comment]
It might be related to https://github.com/redhat-cip/neutron-l3-healthcheck/pull/3 - can you confirm?

**Comment by trihoangvo** [comment]
yes, thank you
